version: 0.2
cache:
  paths:
  - ~/.cache/pip/**/*
  - ~/.m2
phases:
  install:
    runtime-versions:
      python: 3.8
      java: corretto8
    commands:
      - pip install cloudformation-cli-java-plugin
  pre_build:
    commands:
    - echo "Building with Python - $(python --version)"
    - echo "Building with Java - $(java -version)"
  build:
    commands:
    - mvn package
    - cfn submit --dry-run
    - '[ ! -z "$CODEBUILD_WEBHOOK_TRIGGER" ] && cp proserve-cloudformation-stackinstances.zip proserve-cloudformation-stackinstances-$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed "s/tag\///").zip'
  post_build:
    commands:
    - echo Build completed on $(date)
artifacts:
  files:
  - cfn-provider-registration.yaml
  - proserve-cloudformation-stackinstances*

 